import type { LocaleCopy } from '@/lib/types';

export const COPY: Record<'en' | 'zh', LocaleCopy> = {
  en: {
    actions: {
      analyze: 'Analyze Request',
      cancel: 'Reset',
      create: 'Create Item',
      delete: 'Delete',
      refresh: 'Refresh',
      save: 'Save Changes',
    },
    badges: {
      aiSuggested: 'AI structured this request',
      allDay: 'All-day',
      demoFallback: 'Fallback parser active',
      needsConfirmation: 'Needs confirmation',
    },
    labels: {
      dueDate: 'Due date',
      end: 'End',
      estimatedMinutes: 'Estimated minutes',
      group: 'Group',
      notes: 'Notes',
      priority: 'Priority',
      source: 'Source text',
      start: 'Start',
      status: 'Status',
      title: 'Title',
      type: 'Type',
    },
    sections: {
      calendar: 'Calendar deck',
      confirmation: 'Confirmation card',
      editor: 'Item editor',
      history: 'Activity timeline',
      intake: 'Natural-language intake',
      todo: 'To-do rail',
    },
  },
  zh: {
    actions: {
      analyze: '解析事项',
      cancel: '清空',
      create: '创建事项',
      delete: '删除',
      refresh: '刷新',
      save: '保存修改',
    },
    badges: {
      aiSuggested: 'AI 已结构化解析',
      allDay: '全天',
      demoFallback: '当前使用回退解析器',
      needsConfirmation: '需要确认',
    },
    labels: {
      dueDate: '日期',
      end: '结束时间',
      estimatedMinutes: '预计耗时',
      group: '分组',
      notes: '备注',
      priority: '优先级',
      source: '原始输入',
      start: '开始时间',
      status: '状态',
      title: '标题',
      type: '类型',
    },
    sections: {
      calendar: '日历视图',
      confirmation: '确认卡片',
      editor: '事项编辑',
      history: '操作时间线',
      intake: '自然语言录入',
      todo: '待办列表',
    },
  },
};
